### ISSUE TITLE
Bypass

### ISSUE THREAD

**Issue by maitreGits** [leonnnn/pyxtrlock#19] opened 2018-06-08 07:49 UTC
When typing "P" outside of the terminal, it unlocks the screenLocker.

**Comment by sebastianriese** [comment] 2018-06-08 13:41
Could you be more specific? I cannot reproduce the problem with the sparse description you give. Outside which terminal? Also: Which version of pyxtrlock are you using (the latest release? some other commit?). Also, which operating system and windowing system/window manager are you using (note, that pyxtrlock only works on Linux, since the PAM layers of other *nix operating systems are not compatible).

**Comment by sebastianriese** [comment] 2018-06-18 23:19
While we take possible by-passes seriously, we cannot reproduce this bypass, or even understand the description of the conditions under which it occurs. Therefore, I will close this issue for being non-reproducible. Please reopen this issue if you can provide more details that substantiate your claim.

**Closed by sebastianriese** 2018-06-18 23:19 UTC
